### ISSUE TITLE
Current version (0.6.0) fails to build/install with Ruby 2.5 & Rails 5.2 on Windows 10

### ISSUE THREAD

**Issue by Grace** [deepfryed/http-parser-lite#7]
Similar issue seen with the ffi gem: https://github.com/ffi/ffi/issues/598

![image](https://user-images.githubusercontent.com/14958021/47728755-5dcea000-dc35-11e8-9757-0d0cbc6aa919.png)

**Comment by deepfryed** [comment]
fixed in v1.0.0 / b68db69652e590039b38cd7a51fb9a2c6ad52873
